# Generated by Django 5.2.5 on 2025-08-07 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('Location_longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('type', models.CharField(max_length=25)),
                ('serial_number', models.IntegerField(max_length=10)),
                ('description', models.TextField(max_length=300)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('is_rented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsedSensorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ManyToManyField(related_name='used_sensors', to='sensors.sensormodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_sensors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
